### ISSUE TITLE
2) Create a launch pools contract

### ISSUE THREAD

**Issue by zingleton** [MaxosLLC/LaunchPools#2]
Create a launch pools solidity contract

DECISIONS
Do we need a new launch pool contract deployment for each pool? Or, can we make an array of pools?

Function: Create a pool

Data for a Launch Pool
* Expiration date
* Count. The number of the next stake (starting at 1)
* New staking allowed?
* Commitment allowed?
* Maximum commitment value
* Minimum commitment value

**Comment by vhromek** [comment]
We use LaunchBoard to store Launch Pool objects
