### ISSUE TITLE
3) Add stakes to a launch pool

### ISSUE THREAD

**Issue by zingleton** [MaxosLLC/LaunchPools#3]
Add the stakes data structure.

DECISION
What is the data structure?

Do we want to allow any ERC20 token? Or only a token from a list?

DATA
* Owner
* Qualified? Is the owner qualified to invest in this offering. This is something that the pool sponsor sets, after figuring out the requirements for the final investment offer.  This should be attached to a stake owner, and not a stake. But, maybe we will not have a stake owner data structure.
* Order, the count at the time of staking
* Staked token. Is this represented by a contract address? The staking pool will own the staked tokens. We will have a list of tokens that we allow. 
* Value. We can estimate the value. In the first version, we can require stablecoins, which have a specific value. Before committing, it will give people a weight in the voting. After committing, it will hold the true value that we sold the stake for.
* Commitment. This has three values, which we can interpret as “not committed”, “committed”, and “committed if other commitments reach the minimum”

FUNCTIONS
* Add a stake. This will take the stake from the owner. We need some transactions to test this. This needs to be very reliable.
* Remove a stake, and send back to the owners wallet

**Comment by kobby-pentangeli** [comment]
LaunchPools' staking contract successfully implemented. Closing this issue now.
